default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: cccuser
  password: cccuser
  # If you using docker the host should be "db"
  host: localhost
  port: 5432

development:
 <<: *default
 database: flipper_development

test:
 <<: *default
 database: flipper_test

production:
 <<: *default
 database: flipper_prouction
